<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PhotoAdjust</AssemblyName>
    <ApplicationIcon>app-icon.ico</ApplicationIcon>
    <RootNamespace>PhotoAdjust</RootNamespace>
    <Product>高考图片合规调整工具</Product>
    <AssemblyTitle>高考图片合规调整工具</AssemblyTitle>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

</Project>
